global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hardhat'
    static_configs:
      - targets: ['hardhat-node:8545']
